### ISSUE TITLE
Plugin not registered: Resonance Audio Renderer

### ISSUE THREAD

**Issue by EgilSandfeld** [resonance-audio/resonance-audio-wwise-sdk#1]
Hi guys.

Dealing with an issue on iOS platform using Unity (2017.2.0f3), where the Resonance Audio Renderer (v1.1.1) doesn't register with Wwise (2017.2.0) on start-up. This is the message I'm getting (lower right of screen):

**_"AK Error: Could not register plugin ResonanceAudioFX"_**
![inkedmedia-20180118_li](https://user-images.githubusercontent.com/5029330/35093946-1d479fe0-fc44-11e7-99d7-a9350c997966.jpg)

Profiling with Wwise to the iPhone 5s reveals the same issue:
![capture](https://user-images.githubusercontent.com/5029330/35094086-8bd42f78-fc44-11e7-84b8-01855467f9e6.PNG)

As you can see in the left side of the first screenshot of Xcode, the actual library is included in the Xcode project (the libResonanceAudioFX.a). It was included by Unity during Build. That said, I've also tried to manually add the file to the Xcode project and in various places. Though it's now residing in just the Libraries root folder, I've tried other locations without change of result:
_Libraries/Wwise/Deployment/Plugins/iOS/DSP
Libraries/Wwise/Deployment/Plugins/iOS/Profile/lib_

Furthermore I've attempted to force register the plugin via the C# code in Unity using the following in an Awake method:
`AkSoundEngine.RegisterPluginDLL("ResonanceAudioFX");`
which did not help either. Same issue.

Finally, my PluginInfo.xml of my iOS Soundbanks looks like this:
![capture](https://user-images.githubusercontent.com/5029330/35094397-6ab6fcde-fc45-11e7-81d3-f4e9333949dc.PNG)

The Resonance Audio Renderer works great in all other platforms I've tested:
Wwise Editor
Unity Editor (Windows)
Unity Editor (Mac)
Android build

What am I doing wrong? I've previously run GVR Audio Renderer with iOS which works without problems.
Let me know if you need further data!

**Comment by mgorzel** [comment]
Thanks a lot @EgilSandfeld for reporting this issue! We will try to reproduce it based on your info and will get back to you asap!

**Comment by anokta** [comment]
Hi Egil,

I can see one potential step missing in your setup for the iOS build. Could you verify if you copy the [ResonanceAudioFXFactory.h](https://github.com/resonance-audio/resonance-audio-wwise-sdk/blob/master/SDK/include/AK/Plugin/ResonanceAudioFXFactory.h) header file as well into the same folder that you copy the iOS library into (Assets/Wwise/Deployment/Plugins/iOS/DSP)? 

That solves the registration issue for me.

**Comment by EgilSandfeld** [comment]
Thanks for the speedy response :)

Anokta, sorry I can't check that now again, but I'm pretty sure I did check that earlier in my many different attempts, which didn't work. Furthermore I tried moving the ResonanceAudioFXFactory.h around in different other folders in the Xcode project, without result.

But I made it work again now! Just to iterate, issue was with the following combination:

> Unity 2017.2.0f3
Wwise 2017.2.0
Wwise Integration 2017.2.0
Resonance Audio 1.1.1

I then tried downgrading various things, which at first did not help:

> Unity 2017.2.0f3
Wwise 2017.2.0
Wwise Integration 2017.2.0
Resonance Audio 1.0.0

Then I downgraded the Wwise project, Wwise integration and kept the older RA:

> Unity 2017.2.0f3
Wwise 2017.1.3
Wwise Integration 2017.1.3
Resonance Audio 1.0.0

This works! :) So with this in mind, I actually cannot say if the issue lies in the project files (corrupt files perhaps?), if it's the Wwise newer version, or if it's RA giving me trouble. I can just confirm that on my end, the last combination works.
Due to a soon-coming deadline, I'll keep it as it is now with the last combination. In future projects I might want to give it a go with the newer RA and newer Wwise.
Thanks for the help!

**Comment by anokta** [comment]
Interesting results, thanks for sharing! 

FYI, closing the issue, but feel free to re-open/create a new one, in case you encounter the issue again.

**Comment by EgilSandfeld** [comment]
Hi again :)

I experience the exact same issue on a new project using 

Wwise 2017.2.1
Unity 2017.3.0f3
Wwise Integration 2017.2.1
Resonance Audio 1.1.1

![inkedmvimg_20180207_142620_li](https://user-images.githubusercontent.com/5029330/35919020-096cc114-0c14-11e8-97e6-86c16fd4da86.jpg)


> Hi Egil,

> I can see one potential step missing in your setup for the iOS build. Could you verify if you copy the ResonanceAudioFXFactory.h header file as well into the same folder that you copy the iOS library into (Assets/Wwise/Deployment/Plugins/iOS/DSP)?

> That solves the registration issue for me.

I did exactly that for this project , Anokta. Issue persists though audio comes through all fine, it's only RA not working..

Let me know if you need further info! It might not be a bug on your end - it might as well be using Wwise 2017.2.x but I can't tell.

**Comment by EgilSandfeld** [comment]
@anokta Sorry for mentioning you, but wasn't sure if a new post to a closed issue would appear?
